import type { PipelineEntry, Trip, TravelGroup, TripWithGroup } from "./types";

export const demoGroups: TravelGroup[] = [
  {
    id: "g1",
    ownerId: "u1",
    name: "The Kim Family",
    organizerFirst: "Sarah",
    homeCity: "Austin",
    homeState: "TX",
    adults: 2,
    kidsCount: 2,
    kidsAges: [7, 9],
    experienceLevel: "few_times",
    pastVisits: 3,
    vipExperience: false,
    pace: "balanced",
    interests: ["rides", "food", "characters"],
    bio: "Easygoing TX family — kids love dark rides and Mickey waffles. Open to teaming up.",
    completenessScore: 92,
    isPublished: true,
    agentReviewed: true,
  },
  {
    id: "g2",
    ownerId: "u2",
    name: "Team Tatum",
    organizerFirst: "Marcus",
    homeCity: "Brooklyn",
    homeState: "NY",
    adults: 2,
    kidsCount: 1,
    kidsAges: [8],
    experienceLevel: "first_time",
    pastVisits: 0,
    vipExperience: false,
    pace: "balanced",
    interests: ["rides", "characters", "food"],
    bio: "First trip ever, son turning 9. Want a guide so we don't waste a minute.",
    completenessScore: 88,
    isPublished: true,
  },
  {
    id: "g3",
    ownerId: "u3",
    name: "Raj-Patel Crew",
    organizerFirst: "Priya",
    homeCity: "San Jose",
    homeState: "CA",
    adults: 2,
    kidsCount: 2,
    kidsAges: [6, 10],
    experienceLevel: "frequent",
    pastVisits: 7,
    vipExperience: true,
    pace: "maximize",
    interests: ["thrill", "star_wars", "rides"],
    bio: "AP holders, mostly chasing Galaxy's Edge. Love a packed day.",
    completenessScore: 95,
    isPublished: true,
    agentReviewed: true,
  },
  {
    id: "g4",
    ownerId: "u4",
    name: "The Lopez Twins",
    organizerFirst: "Jenna",
    homeCity: "Chicago",
    homeState: "IL",
    adults: 2,
    kidsCount: 2,
    kidsAges: [7, 7],
    experienceLevel: "few_times",
    pastVisits: 2,
    vipExperience: false,
    pace: "relaxed",
    interests: ["food", "characters"],
    bio: "Twin 7yo girls. Pace it slow, lots of snack breaks, character dinners.",
    completenessScore: 90,
    isPublished: true,
  },
  {
    id: "g5",
    ownerId: "u5",
    name: "Devin & Kate",
    organizerFirst: "Devin",
    homeCity: "Orlando",
    homeState: "FL",
    adults: 2,
    kidsCount: 0,
    kidsAges: [],
    experienceLevel: "frequent",
    pastVisits: 12,
    vipExperience: true,
    pace: "maximize",
    interests: ["thrill", "star_wars", "rides", "food"],
    bio: "Locals, no kids. Looking to fill a VIP day with another adult/teen group.",
    completenessScore: 96,
    isPublished: true,
    agentReviewed: true,
  },
  {
    id: "g6",
    ownerId: "u6",
    name: "Farouk Family",
    organizerFirst: "Rashid",
    homeCity: "Toronto",
    homeState: "ON",
    adults: 2,
    kidsCount: 3,
    kidsAges: [5, 8, 11],
    experienceLevel: "few_times",
    pastVisits: 2,
    vipExperience: false,
    pace: "balanced",
    interests: ["rides", "food", "mixed"],
    bio: "Three kids spread out in age. Hoping a VIP day keeps everyone happy.",
    completenessScore: 85,
    isPublished: true,
  },
];

export const demoTrips: Trip[] = [
  {
    id: "t1",
    groupId: "g1",
    arrival: "2026-05-12",
    departure: "2026-05-17",
    idealVipDays: ["2026-05-14"],
    flexible: true,
    openSeats: 3,
    willingness: "either",
    status: "seeking",
    parkDays: {
      "2026-05-13": "EPCOT",
      "2026-05-14": "MK",
      "2026-05-15": "HS",
    },
  },
  {
    id: "t2",
    groupId: "g2",
    arrival: "2026-05-13",
    departure: "2026-05-18",
    idealVipDays: ["2026-05-14", "2026-05-15"],
    flexible: true,
    openSeats: 4,
    willingness: "join",
    status: "seeking",
    parkDays: {
      "2026-05-14": "MK",
      "2026-05-15": "HS",
      "2026-05-16": "AK",
    },
  },
  {
    id: "t3",
    groupId: "g3",
    arrival: "2026-05-12",
    departure: "2026-05-16",
    idealVipDays: ["2026-05-14"],
    flexible: false,
    openSeats: 2,
    willingness: "host",
    status: "seeking",
    parkDays: { "2026-05-14": "HS", "2026-05-15": "HS" },
  },
  {
    id: "t4",
    groupId: "g4",
    arrival: "2026-06-23",
    departure: "2026-06-29",
    idealVipDays: ["2026-06-25"],
    flexible: true,
    openSeats: 2,
    willingness: "either",
    status: "partial",
    parkDays: {
      "2026-06-24": "MK",
      "2026-06-25": "MK",
      "2026-06-26": "EPCOT",
    },
  },
  {
    id: "t5",
    groupId: "g5",
    arrival: "2026-06-24",
    departure: "2026-06-28",
    idealVipDays: ["2026-06-25", "2026-06-26"],
    flexible: true,
    openSeats: 6,
    willingness: "host",
    status: "seeking",
    parkDays: { "2026-06-25": "HS", "2026-06-26": "MK" },
  },
  {
    id: "t6",
    groupId: "g6",
    arrival: "2026-06-22",
    departure: "2026-06-29",
    idealVipDays: ["2026-06-25"],
    flexible: true,
    openSeats: 1,
    willingness: "join",
    status: "seeking",
    parkDays: {
      "2026-06-24": "AK",
      "2026-06-25": "MK",
      "2026-06-26": "EPCOT",
    },
  },
  {
    id: "t7",
    groupId: "g1",
    arrival: "2026-07-08",
    departure: "2026-07-13",
    idealVipDays: ["2026-07-10"],
    flexible: false,
    openSeats: 4,
    willingness: "host",
    status: "seeking",
    parkDays: { "2026-07-09": "MK", "2026-07-10": "MK" },
  },
  {
    id: "t8",
    groupId: "g2",
    arrival: "2026-07-09",
    departure: "2026-07-14",
    idealVipDays: ["2026-07-10"],
    flexible: true,
    openSeats: 3,
    willingness: "join",
    status: "seeking",
    parkDays: { "2026-07-10": "MK", "2026-07-11": "AK" },
  },
];

export const demoPipeline: PipelineEntry[] = [
  { tripId: "t1", stage: "exploring", notes: "Sarah is high-intent. Wants confirmation by 4/30.", updatedAt: "2026-04-14" },
  { tripId: "t4", stage: "coordinating", notes: "Waiting on Devin to confirm guide preference.", updatedAt: "2026-04-15" },
  { tripId: "t2", stage: "new", updatedAt: "2026-04-15" },
  { tripId: "t3", stage: "new", updatedAt: "2026-04-15" },
  { tripId: "t5", stage: "matched", notes: "Matched with Lopez twins — agent intro sent.", updatedAt: "2026-04-15" },
  { tripId: "t6", stage: "exploring", updatedAt: "2026-04-13" },
];

export function tripWithGroup(t: Trip): TripWithGroup {
  const group = demoGroups.find((g) => g.id === t.groupId)!;
  return { ...t, group };
}

export const demoTripsWithGroups: TripWithGroup[] = demoTrips.map(tripWithGroup);
